<?php
  session_start();

  include("../php/config.php");
  if(!isset($_SESSION['valid'])){
    header("Location: ./home.php ");
  }
?>

<?php 
$set_title = "About";
require("../common/head.php"); 
?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <?php require("inc.php"); ?>
  </head>
  <body>
        <!--NavBar Start-->
    <header class="header">


          <!--Profile Content-->
          <div class="logo">
                <p style="float:left; margin:35px; "><a href="../pages/homers.html" style="color:white; font-weight: 100; "> Home </a></p>
                    <a href="../php/logout.php"> <button type="button" id="button-logout-edit"class="btn btn-danger" style="float:right; margin: 35px; font: size 10px;font-size: 15px; height:35px; width: 100px; border-radius:5px;">Log Out</button> </a>
            </div>
          <!--Profile Content End-->

    </header>
    <!--NavBar End-->
   
    <?php //require("../pages/html/about.html"); ?>
    
<!-- ================================= feedback   ============================================= -->

    <section style="margin-top: 100px; position: fixed;">
      <div style="text-align: justify; font-size: 20px; color: white; margin-left: 40px; margin-right: 10px;" >
        <p style="text-align: center; margin-bottom: 20px;">
        <b>Contact Us</b>
        </p>
        <p>
        Have questions or feedback? We'd love to hear from you! Send feedback to <b>legialassistant@gmail.com</b> for assistance, support, or partnership inquiries. Follow us on for the latest updates and news about Law Assistant AI.
        </p>
        <p>
        Law Assistant AI is intended for informational purposes only and does not constitute legal advice. Users should consult qualified legal professionals for specific legal questions or concerns. While we strive to provide accurate and reliable information, we cannot guarantee the completeness or accuracy of the content generated by our platform.
        Thank you for choosing Law Assistant AI as your trusted legal companion. Together, let's unlock the full potential of technology to transform the practice of law and promote access to justice for all.
        </p>
      </div>
      <div class="row gap" style="margin-left: 20px;">
        <div class="col-sm-6 ">
          <?php require("../php/feedback.php"); ?>
        </div>
        <div class="col-sm-6" style="height: 250px; overflow-y: scroll;">
          <h1 style="color: white;">Comments</h1>
          <?php require("../rest-api/list-fed.php"); ?>
        </div>
      </div>
    </section>

    <!-- Swiper JS -->
    <script src="swiper-bundle.min.js"></script>

    <!-- JavaScript -->
    <script src="script.js"></script>
  </body>
</html>
